### ISSUE TITLE
About the input

### ISSUE THREAD

**Issue by YuehChuan** [chenhbo/FUNSR#1]
Hi chenhbo, thanks for sharing this project, I wonder the input is Pose of the  Ultrasound probe, and US images without segmentation?
I wonder is there example input data. 
https://zenodo.org/records/8004388
I found this, where I can use the .ply
Thank you,
e.g. 
python run_normalizedSpace.py --gpu 0 --conf confs/conf.conf --dataname case000007.nii  --dir case000070.nii

**Comment by chenhbo** [comment]
Hi, Thank you for your interest.
I upload an example file of case0000070.nii_ds.ply. 
Here, the point cloud is downsampled to the size of 20000*3.

As for Public Dataset #4, you can use ```numpy.where()``` to extract the point cloud (XYZ coordinates) from the segmented .nii files.
With these points,  using ```open3d->farthest_point_down_sample``` and ```open3d.io->write_point_cloud```
to get the downsampled *.ply file.

**Comment by YuehChuan** [comment]
![charm](https://github.com/user-attachments/assets/f8f6b5c2-c8a8-4ad8-a1f4-44fb28125b85)
Thank you for your support!
It works charm! 
:)

**Comment by YuehChuan** [comment]
![mesh](https://github.com/user-attachments/assets/911347be-ac86-4c3f-acbf-0536741a82b5)

Environment:
ubuntu18.04 CUDA11.4  1080ti graphic card
MeshLab2020.02-linux 
python3.8 
python environmnet I use venv 
python -m venv venv
source venv/bin/activate

note:
PyMCubes==0.1.4

pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
pip install open3d
pip install tqdm pyhocon==0.3.57 trimesh PyMCubes==0.1.4 scipy matplotlib

**Comment by chenhbo** [comment]
Thank you for your feedback!

**Comment by chenhbo** [comment]
This issue will be closed. Feel free to open a new issue if you have questions.
Thx.
